// This file will be auto-generated by Supabase CLI
// For now, we define a basic structure as a placeholder
// Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > src/types/database.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          user_id: string
          email: string
          full_name: string
          phone: string | null
          role: string
          avatar_url: string | null
          company_name: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          email: string
          full_name: string
          phone?: string | null
          role?: string
          avatar_url?: string | null
          company_name?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          email?: string
          full_name?: string
          phone?: string | null
          role?: string
          avatar_url?: string | null
          company_name?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      projects: {
        Row: {
          id: string
          client_id: string
          title: string
          description: string
          service_type: string
          status: string
          budget_range: string | null
          start_date: string | null
          end_date: string | null
          assigned_staff_id: string | null
          progress_percentage: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          client_id: string
          title: string
          description: string
          service_type: string
          status?: string
          budget_range?: string | null
          start_date?: string | null
          end_date?: string | null
          assigned_staff_id?: string | null
          progress_percentage?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          client_id?: string
          title?: string
          description?: string
          service_type?: string
          status?: string
          budget_range?: string | null
          start_date?: string | null
          end_date?: string | null
          assigned_staff_id?: string | null
          progress_percentage?: number
          created_at?: string
          updated_at?: string
        }
      }
      appointments: {
        Row: {
          id: string
          client_id: string
          service_type: string
          preferred_date: string
          preferred_time: string
          status: string
          notes: string | null
          meeting_link: string | null
          staff_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          client_id: string
          service_type: string
          preferred_date: string
          preferred_time: string
          status?: string
          notes?: string | null
          meeting_link?: string | null
          staff_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          client_id?: string
          service_type?: string
          preferred_date?: string
          preferred_time?: string
          status?: string
          notes?: string | null
          meeting_link?: string | null
          staff_id?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      quotes: {
        Row: {
          id: string
          client_id: string
          project_title: string
          service_type: string
          description: string
          budget_range: string | null
          timeline: string | null
          status: string
          quoted_amount: number | null
          valid_until: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          client_id: string
          project_title: string
          service_type: string
          description: string
          budget_range?: string | null
          timeline?: string | null
          status?: string
          quoted_amount?: number | null
          valid_until?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          client_id?: string
          project_title?: string
          service_type?: string
          description?: string
          budget_range?: string | null
          timeline?: string | null
          status?: string
          quoted_amount?: number | null
          valid_until?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      payments: {
        Row: {
          id: string
          project_id: string
          client_id: string
          amount: number
          currency: string
          method: string
          status: string
          transaction_id: string | null
          mpesa_receipt: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          project_id: string
          client_id: string
          amount: number
          currency?: string
          method: string
          status?: string
          transaction_id?: string | null
          mpesa_receipt?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          project_id?: string
          client_id?: string
          amount?: number
          currency?: string
          method?: string
          status?: string
          transaction_id?: string | null
          mpesa_receipt?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      documents: {
        Row: {
          id: string
          project_id: string
          title: string
          description: string | null
          file_url: string
          file_type: string
          file_size: number
          uploaded_by: string
          created_at: string
        }
        Insert: {
          id?: string
          project_id: string
          title: string
          description?: string | null
          file_url: string
          file_type: string
          file_size: number
          uploaded_by: string
          created_at?: string
        }
        Update: {
          id?: string
          project_id?: string
          title?: string
          description?: string | null
          file_url?: string
          file_type?: string
          file_size?: number
          uploaded_by?: string
          created_at?: string
        }
      }
      portfolio: {
        Row: {
          id: string
          title: string
          description: string
          service_type: string
          images: string[]
          featured: boolean
          client_name: string | null
          completion_date: string | null
          location: string | null
          created_at: string
        }
        Insert: {
          id?: string
          title: string
          description: string
          service_type: string
          images: string[]
          featured?: boolean
          client_name?: string | null
          completion_date?: string | null
          location?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          title?: string
          description?: string
          service_type?: string
          images?: string[]
          featured?: boolean
          client_name?: string | null
          completion_date?: string | null
          location?: string | null
          created_at?: string
        }
      }
      contact_messages: {
        Row: {
          id: string
          name: string
          email: string
          phone: string | null
          subject: string
          message: string
          status: string
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          email: string
          phone?: string | null
          subject: string
          message: string
          status?: string
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          email?: string
          phone?: string | null
          subject?: string
          message?: string
          status?: string
          created_at?: string
        }
      }
      notifications: {
        Row: {
          id: string
          user_id: string
          title: string
          message: string
          type: string
          read: boolean
          link: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          title: string
          message: string
          type: string
          read?: boolean
          link?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          title?: string
          message?: string
          type?: string
          read?: boolean
          link?: string | null
          created_at?: string
        }
      }
      activity_logs: {
        Row: {
          id: string
          user_id: string
          action: string
          entity_type: string
          entity_id: string
          details: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          action: string
          entity_type: string
          entity_id: string
          details?: Json | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          action?: string
          entity_type?: string
          entity_id?: string
          details?: Json | null
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      user_role: 'potential_client' | 'existing_client' | 'admin' | 'staff' | 'partner'
      project_status: 'inquiry' | 'quoted' | 'active' | 'on_hold' | 'completed' | 'cancelled'
      service_type: 'architectural_design' | 'interior_design' | 'urban_planning' | 'project_management'
      appointment_status: 'pending' | 'confirmed' | 'completed' | 'cancelled'
      payment_status: 'pending' | 'processing' | 'completed' | 'failed' | 'refunded'
      payment_method: 'mpesa' | 'stripe' | 'bank_transfer'
    }
  }
}
